[package]
name = "rustmachine-regression"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
rand = "0.8.4"
rusty-machine = "0.5.4"
serde = "1.0.130"
serde_derive = "1.0.130"
